---
- hosts: dev
  name: Install docker on ubuntu 22.04
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
        update_cache: true

    - name: Install Docker Engine, containerd
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Make sure docker is enabled and started
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
        append: true
